### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by PocoPongo** [Marctraider/LiveScript-LTSC-21H2#1]
I find the script very good. Thanks.
Unfortunately I can't install an update after running it.

Windows version is 19044.1288.

Maybe I could get a tip on what it could be.

**Comment by Marctraider** [comment]
Hi!

You should just be able to manually enable Windows Update service, and it should be possible to run a cumulative update from i.e. Windows Update Catalog.

Works on all my systems.

Afterwards (after reboot and update applied), run script again, and the update services is once again disabled.
